New Feature Update
timfarkas/Serenify pull request #63
Opened 2024-11-24 14:17 UTC by BruceZZhao

1. Created 2 new entities as Notification and Forum
2. Completed forum feature
3. Completed notification box
4. Enhanced MHWP dashboard 
5. Completed MHWP rating feature

2024-11-24 14:26 UTC, tt01924 approved these changes

2024-11-25 16:30 UTC, timfarkas requested changes
pls don't add the pycache stuff, it's in .gitignore so that it's ignored when doing git add .

I noticed that you added the files via upload (which is probably why the .gitignore didnt work), if you want I can give you a short 101 on using the GitHub command line interface which is much more powerful and versatile! :))

2024-11-25 17:51 UTC, bielasekk approved these changes

2024-11-26 12:51 UTC, timfarkas approved these changes
approving with note to self to remove pycache again

2024-11-26 12:52 UTC, timfarkas commented
@BruceZZhao merged and solved conflict by removing the error classes, if it crashes again pls remove the imports related to those errors

2024-11-26 12:53 UTC, merged