Bullet proofing
timfarkas/Serenify pull request #81
Opened 2024-11-29 22:21 UTC by tt01924

2024-12-01 00:17 UTC, timfarkas requested changes

2024-12-01 00:17 UTC, timfarkas commented on .gitignore
> +database/__pycache__/
the star makes pycache ignored in all directories, pycache is tracked in your repo because someone keeps uploading it to remote (making it tracked on local, too) haha
git rm database/pycache should do the trick
pls leave the .gitignore as it is, lest we haven even more pycache

2024-12-01 00:22 UTC, timfarkas approved these changes

2024-12-01 00:23 UTC, timfarkas commented
removed pycache in this branch, auto merging should work once my rm pycache PR is approved

2024-12-02 12:11 UTC, bielasekk approved these changes

2024-12-02 12:11 UTC, merged